[package]
name = "Examples"
version = "0.0.0"

[addresses]
hello_blockchain = "0xba53a8a5071caf1ea92dd6406687159e43dfec6bc138f7e6789765ac4791ee51"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "testnet" }
